name: "Skrooge Cost Estimator"
description: "Run skrooge cost estimation and comment results on PRs"

inputs:
  replicas:
    description: "Number of replicas in the deployment"
    required: false
    default: "1"
  cpu:
    description: "CPU change in milli-cores"
    required: false
    default: "0"
  mem:
    description: "Memory change in MiB"
    required: false
    default: "0"
  instance:
    description: "Instance type this deployment is running on"
    required: true
  cost-class:
    description: "Type of cost to calculate"
    required: false
    default: "sud"
  region:
    description: "Region to use for cost calculation"
    required: false
    default: "us-central1"
  format:
    description: "Output format (english or json)"
    required: false
    default: "english"
  github-token:
    description: "GitHub token for commenting on PRs"
    required: true
  comment-prefix:
    description: "Prefix for the comment (useful for multiple runs)"
    required: false
    default: "## 💰 Skrooge Cost Estimate"

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install skrooge
      shell: bash
      run: |
        pip install skrooge

    - name: Run skrooge estimate
      id: skrooge-output
      shell: bash
      run: |
        OUTPUT=$(skrooge estimate \
          --replicas ${{ inputs.replicas }} \
          --cpu ${{ inputs.cpu }} \
          --mem ${{ inputs.mem }} \
          --instance ${{ inputs.instance }} \
          --cost-class ${{ inputs.cost-class }} \
          --region ${{ inputs.region }} \
          --format ${{ inputs.format }})
        echo "output<<EOF" >> $GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const output = `${{ steps.skrooge-output.outputs.output }}`;
          const comment = `${{ inputs.comment-prefix }}

          \`\`\`
          ${output}
          \`\`\`

          *Generated by [skrooge](https://github.com/getsentry/skrooge) - A Kubernetes cost estimator*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
