# Artisinally hand-curated from https://github.com/doitintl/gcpinstances.info/blob/master/scraper.py

instance_types = {
    "c2-standard-4": {
        "cpu": 4,
        "memory": 16,
        "local_ssd": 1,
        "network_egress": 10,
        "benchmark": 77310,
    },
    "c2-standard-8": {
        "cpu": 8,
        "memory": 32,
        "local_ssd": 1,
        "network_egress": 16,
        "benchmark": 148689,
    },
    "c2-standard-16": {
        "cpu": 16,
        "memory": 64,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 313768,
    },
    "c2-standard-30": {
        "cpu": 30,
        "memory": 120,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 571147,
    },
    "c2-standard-60": {
        "cpu": 60,
        "memory": 240,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 1142234,
    },
    "c3-standard-4": {
        "cpu": 4,
        "memory": 16,
        "local_ssd": 0,
        "network_egress": 23,
        "benchmark": 0,
    },
    "c3-standard-8": {
        "cpu": 8,
        "memory": 32,
        "local_ssd": 0,
        "network_egress": 23,
        "benchmark": 0,
    },
    "c3-standard-22": {
        "cpu": 22,
        "memory": 88,
        "local_ssd": 0,
        "network_egress": 23,
        "benchmark": 0,
    },
    "c3-standard-44": {
        "cpu": 44,
        "memory": 176,
        "local_ssd": 0,
        "network_egress": 32,
        "benchmark": 0,
    },
    "c3-standard-88": {
        "cpu": 88,
        "memory": 352,
        "local_ssd": 0,
        "network_egress": 62,
        "benchmark": 0,
    },
    "c3-standard-176": {
        "cpu": 176,
        "memory": 704,
        "local_ssd": 0,
        "network_egress": 100,
        "benchmark": 0,
    },
    "c3-highmem-4": {
        "cpu": 4,
        "memory": 32,
        "local_ssd": 0,
        "network_egress": 23,
        "benchmark": 0,
    },
    "c3-highmem-8": {
        "cpu": 8,
        "memory": 64,
        "local_ssd": 0,
        "network_egress": 23,
        "benchmark": 0,
    },
    "c3-highmem-22": {
        "cpu": 22,
        "memory": 176,
        "local_ssd": 0,
        "network_egress": 23,
        "benchmark": 0,
    },
    "c3-highmem-44": {
        "cpu": 44,
        "memory": 352,
        "local_ssd": 0,
        "network_egress": 32,
        "benchmark": 0,
    },
    "c3-highmem-88": {
        "cpu": 88,
        "memory": 704,
        "local_ssd": 0,
        "network_egress": 62,
        "benchmark": 0,
    },
    "c3-highmem-176": {
        "cpu": 176,
        "memory": 1408,
        "local_ssd": 0,
        "network_egress": 100,
        "benchmark": 0,
    },
    "c3-highcpu-4": {
        "cpu": 4,
        "memory": 8,
        "local_ssd": 0,
        "network_egress": 23,
        "benchmark": 80791,
    },
    "c3-highcpu-8": {
        "cpu": 8,
        "memory": 16,
        "local_ssd": 0,
        "network_egress": 23,
        "benchmark": 160579,
    },
    "c3-highcpu-22": {
        "cpu": 22,
        "memory": 44,
        "local_ssd": 0,
        "network_egress": 23,
        "benchmark": 441256,
    },
    "c3-highcpu-44": {
        "cpu": 44,
        "memory": 88,
        "local_ssd": 0,
        "network_egress": 32,
        "benchmark": 881707,
    },
    "c3-highcpu-88": {
        "cpu": 88,
        "memory": 176,
        "local_ssd": 0,
        "network_egress": 62,
        "benchmark": 1687311,
    },
    "c3-highcpu-176": {
        "cpu": 176,
        "memory": 352,
        "local_ssd": 0,
        "network_egress": 100,
        "benchmark": 3399913,
    },
    "n1-standard-1": {
        "cpu": 1,
        "memory": 3.75,
        "local_ssd": 1,
        "network_egress": 2,
        "benchmark": 20090,
    },
    "n1-standard-2": {
        "cpu": 2,
        "memory": 7.5,
        "local_ssd": 1,
        "network_egress": 10,
        "benchmark": 26532,
    },
    "n1-standard-4": {
        "cpu": 4,
        "memory": 15,
        "local_ssd": 1,
        "network_egress": 10,
        "benchmark": 54678,
    },
    "n1-standard-8": {
        "cpu": 8,
        "memory": 30,
        "local_ssd": 1,
        "network_egress": 16,
        "benchmark": 105383,
    },
    "n1-standard-16": {
        "cpu": 16,
        "memory": 60,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 221834,
    },
    "n1-standard-32": {
        "cpu": 32,
        "memory": 120,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 440755,
    },
    "n1-standard-64": {
        "cpu": 64,
        "memory": 240,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 883369,
    },
    "n1-standard-96": {
        "cpu": 96,
        "memory": 360,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 1247197,
    },
    "n1-highmem-2": {
        "cpu": 2,
        "memory": 13,
        "local_ssd": 1,
        "network_egress": 10,
        "benchmark": 26438,
    },
    "n1-highmem-4": {
        "cpu": 4,
        "memory": 26,
        "local_ssd": 1,
        "network_egress": 10,
        "benchmark": 54337,
    },
    "n1-highmem-8": {
        "cpu": 8,
        "memory": 52,
        "local_ssd": 1,
        "network_egress": 16,
        "benchmark": 104640,
    },
    "n1-highmem-16": {
        "cpu": 16,
        "memory": 104,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 220547,
    },
    "n1-highmem-32": {
        "cpu": 32,
        "memory": 208,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 439129,
    },
    "n1-highmem-64": {
        "cpu": 64,
        "memory": 416,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 879708,
    },
    "n1-highmem-96": {
        "cpu": 96,
        "memory": 624,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 1248277,
    },
    "n1-highcpu-2": {
        "cpu": 2,
        "memory": 1.8,
        "local_ssd": 1,
        "network_egress": 10,
        "benchmark": 26517,
    },
    "n1-highcpu-4": {
        "cpu": 4,
        "memory": 3.6,
        "local_ssd": 1,
        "network_egress": 10,
        "benchmark": 54676,
    },
    "n1-highcpu-8": {
        "cpu": 8,
        "memory": 7.2,
        "local_ssd": 1,
        "network_egress": 16,
        "benchmark": 105053,
    },
    "n1-highcpu-16": {
        "cpu": 16,
        "memory": 14.4,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 221443,
    },
    "n1-highcpu-32": {
        "cpu": 32,
        "memory": 28.8,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 438006,
    },
    "n1-highcpu-64": {
        "cpu": 64,
        "memory": 57.6,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 874912,
    },
    "n1-highcpu-96": {
        "cpu": 96,
        "memory": 86.4,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 1245251,
    },
    "n2-standard-2": {
        "cpu": 2,
        "memory": 8,
        "local_ssd": 1,
        "network_egress": 10,
        "benchmark": 33676,
    },
    "n2-standard-4": {
        "cpu": 4,
        "memory": 16,
        "local_ssd": 1,
        "network_egress": 10,
        "benchmark": 67643,
    },
    "n2-standard-8": {
        "cpu": 8,
        "memory": 32,
        "local_ssd": 1,
        "network_egress": 16,
        "benchmark": 135272,
    },
    "n2-standard-16": {
        "cpu": 16,
        "memory": 64,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 269760,
    },
    "n2-standard-32": {
        "cpu": 32,
        "memory": 128,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 538050,
    },
    "n2-standard-48": {
        "cpu": 48,
        "memory": 192,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 806235,
    },
    "n2-standard-64": {
        "cpu": 64,
        "memory": 256,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 1069840,
    },
    "n2-standard-80": {
        "cpu": 80,
        "memory": 320,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 1338406,
    },
    "n2-standard-96": {
        "cpu": 96,
        "memory": 384,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 1590273,
    },
    "n2-standard-128": {
        "cpu": 128,
        "memory": 512,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 2065382,
    },
    "n2-highmem-2": {
        "cpu": 2,
        "memory": 16,
        "local_ssd": 1,
        "network_egress": 10,
        "benchmark": 33649,
    },
    "n2-highmem-4": {
        "cpu": 4,
        "memory": 32,
        "local_ssd": 1,
        "network_egress": 10,
        "benchmark": 67702,
    },
    "n2-highmem-8": {
        "cpu": 8,
        "memory": 64,
        "local_ssd": 1,
        "network_egress": 16,
        "benchmark": 135364,
    },
    "n2-highmem-16": {
        "cpu": 16,
        "memory": 128,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 269842,
    },
    "n2-highmem-32": {
        "cpu": 32,
        "memory": 256,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 538032,
    },
    "n2-highmem-48": {
        "cpu": 48,
        "memory": 384,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 806506,
    },
    "n2-highmem-64": {
        "cpu": 64,
        "memory": 512,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 1071112,
    },
    "n2-highmem-80": {
        "cpu": 80,
        "memory": 640,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 1330008,
    },
    "n2-highmem-96": {
        "cpu": 96,
        "memory": 768,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 1590062,
    },
    "n2-highmem-128": {
        "cpu": 128,
        "memory": 864,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 2072337,
    },
    "n2-highcpu-2": {
        "cpu": 2,
        "memory": 2,
        "local_ssd": 1,
        "network_egress": 10,
        "benchmark": 33719,
    },
    "n2-highcpu-4": {
        "cpu": 4,
        "memory": 4,
        "local_ssd": 1,
        "network_egress": 10,
        "benchmark": 67817,
    },
    "n2-highcpu-8": {
        "cpu": 8,
        "memory": 8,
        "local_ssd": 1,
        "network_egress": 16,
        "benchmark": 135527,
    },
    "n2-highcpu-16": {
        "cpu": 16,
        "memory": 16,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 270110,
    },
    "n2-highcpu-32": {
        "cpu": 32,
        "memory": 32,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 538530,
    },
    "n2-highcpu-48": {
        "cpu": 48,
        "memory": 48,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 806668,
    },
    "n2-highcpu-64": {
        "cpu": 64,
        "memory": 64,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 1070807,
    },
    "n2-highcpu-80": {
        "cpu": 80,
        "memory": 80,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 1329120,
    },
    "n2-highcpu-96": {
        "cpu": 96,
        "memory": 96,
        "local_ssd": 1,
        "network_egress": 32,
        "benchmark": 0,
    },
}
